export const FETCH_EVENT_DATA_STARTED = 'FETCH_EVENT_DATA_STARTED';
export const FETCH_EVENT_DATA_SUCCESS = 'FETCH_EVENT_DATA_SUCCES';
export const FETCH_EVENT_DATA_FAIL = 'FETCH_EVENT_DATA_FAIL';
export const FETCH_EVENT = 'FETCH_EVENT'; 